### ISSUE TITLE
[SyntaxError: Unexpected token =]

### ISSUE THREAD

**Issue by ghoshnirmalya** [jonathantneal/postcss-partial-import#32] opened 2016-12-25 13:55 UTC
I'm getting this error while compiling on version `3.1.0`.
Issue can be replicated in version `3.0.0` also but the issue is not present in `2.1.0`.

**Comment by jonathantneal** [comment] 2016-12-29 17:54
You’ll need to include more details if you’d like me to debug this. We have a testing suite that runs automatically. https://travis-ci.org/jonathantneal/postcss-partial-import

**Comment by abramz** [comment] 2017-01-19 18:29
Upgrading from `2.1` to `3.1` I get the error below. Issue persists after reinstall.

As that is ES6 syntax, I would guess that the issue is that the published package is not referencing the transpiled code.

```
> postcss -c tools/postcss.js -d web/public/styles web/views/styles/*.css

<DIR>/node_modules/postcss-partial-import/index.js:9
        (opts = {}) => processor(
              ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at <DIR>/node_modules/postcss-cli/index.js:107:14
    at Array.map (native)
    at Object.<anonymous> (<DIR>/node_modules/postcss-cli/index.js:100:24)

npm ERR! Darwin 16.3.0
npm ERR! argv "~/.nvm/versions/node/v4.7.2/bin/node" "~/.nvm/versions/node/v4.7.2/bin/npm" "run" "postcss"
npm ERR! node v4.7.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
```

I believe this should be more than sufficient information for you guys to resolve this.

**Comment by jonathantneal** [comment] 2017-01-19 18:47
Thanks @abramz for including that snippet. The issue there appears to be the ES6 syntax, which is supported in Node 6.5+, although this plugin eagerly [expects 6.9.1+](https://github.com/jonathantneal/postcss-partial-import/blob/master/package.json#L22).

Resolving that issue is a matter of deciding whether this plugin should support Node 4x environments. And then, if it does, how those environments should be supported. It could involve transpiling, yes, or it could involve multiple distributions based on [`process.version`](https://nodejs.org/api/process.html#process_process_version). I’m not certain the answer to any of these questions, because it’s difficult to know the majority user base of PostCSS, nor the performance impact in Node 6 of transpiling the code to Node 4. Without hard facts, it becomes a matter of opinion, and falls back to the user base.

**Comment by abramz** [comment] 2017-01-19 20:23
I understand what you are saying. After posting I dug around the repo a bit more and realized you aren't using babel.

Looking around the ecosystem, `postcss` itself supports [`>=0.12`](https://github.com/postcss/postcss/blob/master/package.json#L6). I looked at a pretty small sample of plugins (~10) and none of them specify `engines`, however 8/10 use babel, so they would at least support down to `node v4`.

In my opinion, libraries should support, at a minimum, the active versions of node, `>=v4`. My team will not be moving off `v4` for a while as some modules we depend on break on `v6` and we have another year of LTS support.

However, you are mostly the only contributor to this open-source plugin, and adding this sort of support puts all the pain on you. 

If my team has to use `v2.1` until we can upgrade to `v6`, then that is what we have to do, it works perfectly well, so it isn't a problem.

**Comment by lkraav** [comment] 2017-01-22 16:30
Just ran into the same thing, gentoo current stable is `nodejs-4.6.1`. Thanks for the breakdown, everyone.

**Comment by jonathantneal** [comment] 2017-03-22 17:23
If there’s a simple pattern to compile out the node v4 version on npm publish, I’d definitely try to get it in.

**Comment by jonathantneal** [comment] 2017-05-11 18:56
This plugin is now Node v4 compatible as of v4.0.0 (fittingly)

**Closed as completed by jonathantneal** 2017-05-11 18:56 UTC

**Comment by abramz** [comment] 2017-05-11 19:05
Awesome man. Thanks so much.
